b list::neyman_sort
display k
display n
display start->value
display start->next->value
display sorted_end->value
display sorted_end->next->value
display sorted.head->value
display sorted.head->next->value
display start_B->value
display start_B->next->value
display end_A->value
display end_A->next->value
display A.head->value
display A.head->next->value
display this->head->value
display this->head->next->value

b list::add_sorted_to_sorted
display l_temp->value
display l_temp->next->value
display len_add
display (*end_A)->value
display (*end_A)->next->value
display added->value
display added->next->value
display added_next->value
display added_next->next->value
display start->value
display start->next->value
display prev_start->value
display prev_start->next->value
display i
display curr->value
display curr->next->value
display prev->value
display prev->next->value
display this->head->value
display this->head->next->value

